### ISSUE TITLE
Contribution Guide Document.

### ISSUE THREAD

**Issue by HarryHeights** [linuxwhatelse/dups#7]
Hello. I'm Harry. I'm a content creator and a copywriter. I contribute to open source projects by creating documents which the project owners require or documents I think they might need but don't know about. I read through your Readme file and noticed you stated the absence of a contributions guidelines. I can help create that document. We'd work together on it though.

**Comment by tadly** [comment]
That certainly sounds interesting and I wouldn't mind a helping hand as documentation is not my strong suit.

Right now `dups` is still in a somewhat alpha state (allowing me to introduce breaking changes) which is why I haven't spent time writing a contribution guide.

Let me know what you need and I'll try to provide :)

**Comment by HarryHeights** [comment]
Alright. I'll get to work right away. When I need an information I'll let you know.

**Comment by tadly** [comment]
Totally forgot this was still open. Done with 19b4947c6d7955ad89ec54f2a48ee967945b0a9c
